package main.java.model;

public enum TipoPromocion {

	PAGUE_X_LLEVE_Y_UNIDADES,
	X_PORCENTAJE_DESCUENTO,
	PAGUE_X_LLEVE_Y_CANTIDAD,
	PAGUE_X_LLEVE_SIGUIENTE_CON_Y_PORCENTAJE_DESCUENTO,
	PAGUE_X_POR_PRODUCTOS_PROMOCION;
}
