/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uniandes.isis2304.superAndes.interfazApp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import main.java.model.Comprador;
import main.java.model.UsuariosComprasRFC10;
import uniandes.isis2304.superAndes.persistencia.PersistenciaSuperAndes;

/**
 *
 * @author Andres
 */
public class DialogoConsumo extends javax.swing.JDialog implements ActionListener {

	private long idSucursal;
	private PersistenciaSuperAndes mundo;
	private List<String> criteriosOrden; 
	private List<Boolean> ascendenciaCriterios;
	private boolean admin;
	private int requerimiento;

	/**
	 * Creates new form DialogoConsGerente
	 */
	public DialogoConsumo(long idSucursal,PersistenciaSuperAndes persistenciaSuperAndes, boolean admin,int requer) {
		this.idSucursal=idSucursal;
		mundo=persistenciaSuperAndes;
		this.admin=admin;
		criteriosOrden=new ArrayList<>();
		ascendenciaCriterios=new ArrayList<>();
		requerimiento=requer;		
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lblFechaIni = new javax.swing.JLabel();
		txtFechaIni = new javax.swing.JTextField();
		lblFechaFin = new javax.swing.JLabel();
		txtFechaFin = new javax.swing.JTextField();
		txtCodigoProducto = new javax.swing.JTextField();
		lblCodigoProd = new javax.swing.JLabel();
		lblCriterioBusq = new javax.swing.JLabel();
		cmbCriterio = new javax.swing.JComboBox<>();
		cmbAscen = new javax.swing.JComboBox<>();
		btnAnadir = new javax.swing.JButton();
		btnConsultar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		lblFechaIni.setText("Fecha Inicial");

		txtFechaIni.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtFechaIniActionPerformed(evt);
			}
		});

		lblFechaFin.setText("Fecha Final");

		txtFechaFin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtFechaFinActionPerformed(evt);
			}
		});

		txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtCodigoProductoActionPerformed(evt);
			}
		});

		lblCodigoProd.setText("Codigo Producto");

		lblCriterioBusq.setText("Criterio de busqueda");

		cmbCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "identificador", "correoElectronico", "fecha", "cantidadVendida", "idProductoSucursal", "idSucursal", "numero" }));

		cmbAscen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASCENDENTE", "DESCENDENTE" }));
		cmbAscen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cmbAscenActionPerformed(evt);
			}
		});

		btnAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uniandes/isis2304/superAndes/interfazApp/dataInterfaz/add.png"))); // NOI18N
		btnAnadir.setActionCommand("ANADIR");
		btnAnadir.addActionListener(this);

		btnConsultar.setText("Consultar");
		btnConsultar.setActionCommand("CONSULTAR");
		btnConsultar.addActionListener(this);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(61, 61, 61)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblFechaFin)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addComponent(lblCodigoProd)
																		.addGap(75, 75, 75))
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addComponent(lblFechaIni)
																		.addGap(97, 97, 97))
																.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
																		.addComponent(lblCriterioBusq)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(cmbCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(cmbAscen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(txtFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(149, 149, 149)
										.addComponent(btnConsultar)))
						.addContainerGap(57, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(45, 45, 45)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblFechaIni))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblFechaFin)
								.addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(10, 10, 10)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblCodigoProd)
								.addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblCriterioBusq)
												.addComponent(cmbCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cmbAscen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(12, 12, 12)
										.addComponent(btnAnadir)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
						.addComponent(btnConsultar)
						.addContainerGap())
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtFechaIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaIniActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtFechaIniActionPerformed

	private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtFechaFinActionPerformed

	private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtCodigoProductoActionPerformed

	private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_btnConsultarActionPerformed

	private void cmbAscenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAscenActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_cmbAscenActionPerformed



	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAnadir;
	private javax.swing.JButton btnConsultar;
	private javax.swing.JComboBox<String> cmbAscen;
	private javax.swing.JComboBox<String> cmbCriterio;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lblCodigoProd;
	private javax.swing.JLabel lblCriterioBusq;
	private javax.swing.JLabel lblFechaFin;
	private javax.swing.JLabel lblFechaIni;
	private javax.swing.JTextField txtCodigoProducto;
	private javax.swing.JTextField txtFechaFin;
	private javax.swing.JTextField txtFechaIni;
	// End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent arg0) {
		// TODO Auto-generated method stub
		String comando = arg0.getActionCommand( );

		if(comando.equals("CONSULTAR"))
		{
			if(requerimiento==10)
			{
				if(admin)
				{
					try {
						List<UsuariosComprasRFC10>usuarios=mundo.RFC10Administrador(txtFechaIni.getText(), txtFechaFin.getText(), txtCodigoProducto.getText(), criteriosOrden, ascendenciaCriterios);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelCompradoresRFC10(usuarios),idSucursal);
						inter.setVisible(true);
						this.dispose();
					}catch (Exception e) {
						e.printStackTrace();
						JOptionPane.showMessageDialog(this, "Revisa los datos\nRecuerda que las fechas son \nde la forma dd/mm/yyyy");

					}
				}
				else {
					try {
						List<UsuariosComprasRFC10>usuarios=mundo.RFC10Administrador(txtFechaIni.getText(), txtFechaFin.getText(), txtCodigoProducto.getText(), criteriosOrden, ascendenciaCriterios);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelCompradoresRFC10(usuarios),idSucursal);
						inter.setVisible(true);
						this.dispose();
					}catch (Exception e) {
						e.printStackTrace();
						JOptionPane.showMessageDialog(this, "Revisa los datos\nRecuerda que las fechas son \nde la forma dd/mm/yyyy");

					}
				}
			}
			else
			{
				if(admin)
				{
					try {
						List<Comprador>usuarios=mundo.RFC11Administrador(idSucursal+"",txtFechaIni.getText(), txtFechaFin.getText(), txtCodigoProducto.getText(), criteriosOrden, ascendenciaCriterios);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelCompradores(usuarios),idSucursal);
						inter.setVisible(true);
						this.dispose();
					}catch (Exception e) {
						e.printStackTrace();
						JOptionPane.showMessageDialog(this, "Revisa los datos\nRecuerda que las fechas son \nde la forma dd/mm/yyyy");

					}
				}
				else {
					try {
						List<Comprador>usuarios=mundo.RFC11Gerente(idSucursal+"",txtFechaIni.getText(), txtFechaFin.getText(), txtCodigoProducto.getText(), criteriosOrden, ascendenciaCriterios);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelCompradores(usuarios),idSucursal);
						inter.setVisible(true);
						this.dispose();
					}catch (Exception e) {
						e.printStackTrace();
						JOptionPane.showMessageDialog(this, "Revisa los datos\nRecuerda que las fechas son \nde la forma dd/mm/yyyy");

					}
				}
			}
		}
		else
		{
			if(!criteriosOrden.contains(cmbCriterio.getSelectedItem().toString()))
			{
				if(cmbAscen.getSelectedItem().equals("ASCENDENTE"))
				{
					ascendenciaCriterios.add(true);
				}
				else
				{
					ascendenciaCriterios.add(false);
				}
				criteriosOrden.add(cmbCriterio.getSelectedItem().toString());
				JOptionPane.showMessageDialog(this, "Se agrego el criterio "+cmbCriterio.getSelectedItem().toString());
			}
			else
			{
				JOptionPane.showMessageDialog(this, "Ya existe ese criterio");

			}
		}


	}
}
