/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uniandes.isis2304.superAndes.interfazApp;

import java.awt.Panel;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import main.java.model.Comprador;
import main.java.model.FacturasComprador;
import main.java.model.IndiceBodega;
import main.java.model.IndiceEstante;
import main.java.model.Pedido;
import main.java.model.Productos;
import main.java.model.Promocion;

import uniandes.isis2304.superAndes.persistencia.PersistenciaSuperAndes;

/**
 *
 * @author Andres
 */
public class InterfazEmpleados extends javax.swing.JFrame {

	private PersistenciaSuperAndes mundo;

	private long idSucursal;

	/**
	 * Creates new form InterfazEmpleados2
	 */
	public InterfazEmpleados(PersistenciaSuperAndes persistencia,long idSucursal) {
		mundo=persistencia;
		this.idSucursal=idSucursal;
		setResizable( false );
		setLocationRelativeTo(null);
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1=new JPanel();
		menuEmpleado = new javax.swing.JMenuBar();
		mnRegistrar = new javax.swing.JMenu();
		opProveedores = new javax.swing.JMenu();
		opProducto = new javax.swing.JMenu();
		opBodega = new javax.swing.JMenu();
		opEstante = new javax.swing.JMenu();
		opPromocion = new javax.swing.JMenu();
		opPedido = new javax.swing.JMenu();
		opLlegadaProducto = new javax.swing.JMenu();
		mnConsultar = new javax.swing.JMenu();
		opDinero = new javax.swing.JMenu();
		opPromociones = new javax.swing.JMenu();
		opOcupacion = new javax.swing.JMenu();
		opProdCarac = new javax.swing.JMenu();
		opCompProv = new javax.swing.JMenu();
		opVentasUsu = new javax.swing.JMenu();
		opAnaOper = new javax.swing.JMenu();
		opCliFrec = new javax.swing.JMenu();
		opProdPocDemanda = new javax.swing.JMenu();
		opConsumo=new javax.swing.JMenu();
		opConsumoV2=new javax.swing.JMenu();
		opFuncionamientoProd=new javax.swing.JMenu();
		opFuncionamientoProv=new javax.swing.JMenu();
		opBuenosClientes=new javax.swing.JMenu();
		mnRecoger = new javax.swing.JMenu();



		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 400, Short.MAX_VALUE)
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 274, Short.MAX_VALUE)
				);

		mnRegistrar.setText("Registrar");

		opProveedores.setText("Proveedor");
		opProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				DialogoCrearProveedor dialog=new DialogoCrearProveedor(mundo);
				dialog.setVisible(true);
			}
		});
		mnRegistrar.add(opProveedores);

		opProducto.setText("Producto");
		opProducto.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				DialogoCrearProducto dialog=new DialogoCrearProducto(mundo);
				dialog.setVisible(true);
			}
		});
		mnRegistrar.add(opProducto);

		opBodega.setText("Bodega");
		opBodega.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				DialogoCrearBodEst dialog=new DialogoCrearBodEst(mundo,DialogoCrearBodEst.BODEGA);
				dialog.setVisible(true);
			}
		});
		mnRegistrar.add(opBodega);

		opEstante.setText("Estante");
		opEstante.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				DialogoCrearBodEst dialog=new DialogoCrearBodEst(mundo,DialogoCrearBodEst.ESTANTE);
				dialog.setVisible(true);
			}
		});
		mnRegistrar.add(opEstante);

		opPromocion.setText("Promocion");
		opPromocion.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				DialogoCrearPromocion dialog=new DialogoCrearPromocion(mundo);
				dialog.setVisible(true);
			}
		});
		mnRegistrar.add(opPromocion);

		opPedido.setText("Pedido");
		opPedido.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				DialogoCrearPedido dialog=new DialogoCrearPedido(mundo);
				dialog.setVisible(true);
			}
		});
		mnRegistrar.add(opPedido);

		opLlegadaProducto.setText("Llegada Producto");
		opLlegadaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {
					String idPedido=JOptionPane.showInputDialog("Digite el id del pedido que llego");                		
					mundo.requerimiento10(Long.valueOf(idPedido));
					JOptionPane.showMessageDialog(null, "Se registro satisfactoriamente la llegada del producto proveniente del pedido "+idPedido);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Registro fallido \nIntentalo con otros datos");
					e.printStackTrace();
				}
			}
		});
		mnRegistrar.add(opLlegadaProducto);

		menuEmpleado.add(mnRegistrar);

		mnConsultar.setText("Consultar");

		opDinero.setText("Dinero Recolectado");
		opDinero.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {
					String fechaIni=JOptionPane.showInputDialog("Digite la fecha inicial de la forma dd/MM/yy");
					String fechaFin=JOptionPane.showInputDialog("Digite la fecha final de la forma dd/MM/yy");

					double dinero=mundo.requerimientoConsulta1(fechaIni, fechaFin);
					JOptionPane.showMessageDialog(null, "Se recogio "+dinero);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
					e.printStackTrace();
				}
			}
		});
		mnConsultar.add(opDinero);

		opPromociones.setText("Promociones populares");
		opPromociones.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	
					List<Promocion> promos=mundo.requerimientoConsulta2();
					InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelPromocion(promos),idSucursal);
					inter.setVisible(true);
					dispose();
				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");

					e.printStackTrace();
				}
			}
		});
		mnConsultar.add(opPromociones);

		opOcupacion.setText("Ocupacion bodegas/estantes");
		opOcupacion.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	

					List<IndiceBodega>indiceBodega=mundo.requerimientoConsulta3_1();
					List<IndiceEstante>indiceEstante=mundo.requerimientoConsulta3_2();
					InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelBodegaEstantes(indiceBodega,indiceEstante),idSucursal);
					inter.setVisible(true);
					dispose();

				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
					e.printStackTrace();
				}
			}
		});
		mnConsultar.add(opOcupacion);

		opProdCarac.setText("Productos por caracteristica");
		opProdCarac.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);

				Object tipo = JOptionPane.showInputDialog(null,"Caracteristica del producto",
						"Seleccione", JOptionPane.QUESTION_MESSAGE, null,
						new Object[] { "Rango Precio","Fecha Vencimiento", "Rango Peso", "Rango Volumen","Proveedor","Ciudad","Sucursal","Categoria","Tipo Producto" },"Seleccione");
				if(tipo.equals("Rango Precio"))
				{
					try {	
						double precioIni=Double.parseDouble(JOptionPane.showInputDialog(null, "Precio inicial"));
						double precioFin=Double.parseDouble(JOptionPane.showInputDialog(null, "Precio final"));

						List<Productos>productos=mundo.requerimientoConsulta4_1(precioIni, precioFin);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
						inter.setVisible(true);
						dispose();  
					} catch (Exception e) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
						e.printStackTrace();
					}
				}else if(tipo.equals("Fecha Vencimiento"))
				{
					try{
						String fecha=JOptionPane.showInputDialog(null, "Fecha Vencimiento");

						List<Productos>productos=mundo.requerimientoConsulta4_2(fecha);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
						inter.setVisible(true);
						dispose();  
					} catch (Exception e) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
						e.printStackTrace();
					}
				}else if(tipo.equals("Rango Peso"))
				{
					try {	
						double pesoIni=Double.parseDouble(JOptionPane.showInputDialog(null, "Peso minimo"));
						double pesoFin=Double.parseDouble(JOptionPane.showInputDialog(null, "Peso maximo"));

						List<Productos>productos=mundo.requerimientoConsulta4_3(pesoIni, pesoFin);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
						inter.setVisible(true);
						dispose();  
					} catch (Exception e) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
						e.printStackTrace();
					}
				}else if(tipo.equals("Rango Volumen"))
				{
					try {	
						double volIni=Double.parseDouble(JOptionPane.showInputDialog(null, "Volumen minimo"));
						double volFin=Double.parseDouble(JOptionPane.showInputDialog(null, "Volumen maximo"));

						List<Productos>productos=mundo.requerimientoConsulta4_4(volIni, volFin);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
						inter.setVisible(true);
						dispose();  
					} catch (Exception e) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
						e.printStackTrace();
					}
				}else if(tipo.equals("Proveedor"))
				{
					try{
						String proveedor=JOptionPane.showInputDialog(null, "Proveedor a buscar");

						List<Productos>productos=mundo.requerimientoConsulta4_5(proveedor);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
						inter.setVisible(true);
						dispose();  
					} catch (Exception e) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
						e.printStackTrace();
					}
				}else if(tipo.equals("Ciudad"))
				{
					try{
						String ciudad=JOptionPane.showInputDialog(null, "Ciudad a buscar");

						List<Productos>productos=mundo.requerimientoConsulta4_6(ciudad);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
						inter.setVisible(true);
						dispose();  
					} catch (Exception e) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
						e.printStackTrace();
					}
				}else if(tipo.equals("Sucursal"))
				{
					try{
						long idSucursal=Long.parseLong(JOptionPane.showInputDialog(null, "Id de la sucursal a buscar"));

						List<Productos>productos=mundo.requerimientoConsulta4_7(idSucursal);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
						inter.setVisible(true);
						dispose();  
					} catch (Exception e) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
						e.printStackTrace();
					}
				}else if(tipo.equals("Categoria"))
				{
					try{
						String categoria=JOptionPane.showInputDialog(null, "Categoria a buscar");

						List<Productos>productos=mundo.requerimientoConsulta4_8(categoria);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
						inter.setVisible(true);
						dispose();  
					} catch (Exception e) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
						e.printStackTrace();
					}
				}else if(tipo.equals("Tipo Producto"))
				{
					try{
						String tipoProducto=JOptionPane.showInputDialog(null, "Tipo de producto a buscar");

						List<Productos>productos=mundo.requerimientoConsulta4_9(tipoProducto);
						InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
						inter.setVisible(true);
						dispose();  
					} catch (Exception e) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
						e.printStackTrace();
					}
				}

			}

		});
		mnConsultar.add(opProdCarac);

		opCompProv.setText("Compras a proveedores");
		opCompProv.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	
					List<Pedido>pedidos=mundo.requerimientoConsulta5();
					InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelPedido(pedidos),idSucursal);
					inter.setVisible(true);
					dispose();  

				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
					e.printStackTrace();
				}
			}
		});
		mnConsultar.add(opCompProv);

		opVentasUsu.setText("Ventas a un usuario");
		opVentasUsu.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	
					String fechaIni=JOptionPane.showInputDialog("Digite la fecha inicial de la forma dd/MM/yy");
					String fechaFin=JOptionPane.showInputDialog("Digite la fecha final de la forma dd/MM/yy");
					String cedula=JOptionPane.showInputDialog("Ingrese por favor el documento del cliente");
					List<FacturasComprador>facturas=mundo.requerimientoConsulta6(fechaIni, fechaFin, cedula);
					InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelFacturasComprador(facturas),idSucursal);
					inter.setVisible(true);
					dispose();    

				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
					e.printStackTrace();
				}
			}
		});
		mnConsultar.add(opVentasUsu);

		opAnaOper.setText("Analizar operacion");
		opAnaOper.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	
					String tipoProd=JOptionPane.showInputDialog("Digite el tipo de los productos");
					Object tipo = JOptionPane.showInputDialog(null,"Rango de tiempo",
							"Seleccione", JOptionPane.QUESTION_MESSAGE, null,
							new Object[] { "Mes Mayor Demanda" ,"Mes Menor Demanda","Mes Mayor Ingresos"},"Seleccione");

					if(tipo.equals("Mes Mayor Demanda"))
					{
						String mes= mundo.requerimientoConsulta7_1(tipoProd);
						JOptionPane.showMessageDialog(null, "El mes con mayor demanda fue "+mes);
					}else if(tipo.equals("Mes Menor Demanda"))
					{
						String mes= mundo.requerimientoConsulta7_2(tipoProd);
						JOptionPane.showMessageDialog(null, "El mes con menor demanda fue "+mes);
					}else if(tipo.equals("Mes Mayor Ingresos"))
					{
						String mes= mundo.requerimientoConsulta7_3(tipoProd);
						JOptionPane.showMessageDialog(null, "El mes con mayor ingresos fue "+mes);
					}


				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
					e.printStackTrace();
				}
			}
		});
		mnConsultar.add(opAnaOper);

		opCliFrec.setText("Clientes frecuentes");
		opCliFrec.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	

					List<Comprador>compradores=mundo.requerimientoConsulta8();
					InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelCompradores(compradores),idSucursal);
					inter.setVisible(true);
					dispose();  

				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
					e.printStackTrace();
				}
			}
		});
		mnConsultar.add(opCliFrec);

		opProdPocDemanda.setText("Productos poca demanda");
		opProdPocDemanda.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	

					List<Productos>productos=mundo.requerimientoConsulta9();
					System.out.println("Hola");
					InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductos(productos),idSucursal);
					inter.setVisible(true);
					dispose();  


				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");
					e.printStackTrace();
				}
			}
		});
		mnConsultar.add(opProdPocDemanda);

		opConsumo.setText("Consumo");
		opConsumo.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	


					Object tipo = JOptionPane.showInputDialog(null,"Rango su cargo",
							"Seleccione", JOptionPane.QUESTION_MESSAGE, null,
							new Object[] { "Gerente" ,"Administrador"},"Seleccione");
					DialogoConsumo dialog;
					if(tipo.toString().equals("Gerente"))
					{
						dialog=new DialogoConsumo(idSucursal,mundo,false,10);
					}
					else
					{
						dialog=new DialogoConsumo(idSucursal,mundo,true,10);
					}
					dialog.setVisible(true);
					dispose();  


				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");

				}
			}
		});
		mnConsultar.add(opConsumo);

		opConsumoV2.setText("ConsumoV2");
		opConsumoV2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	


					Object tipo = JOptionPane.showInputDialog(null,"Rango su cargo",
							"Seleccione", JOptionPane.QUESTION_MESSAGE, null,
							new Object[] { "Gerente" ,"Administrador"},"Seleccione");
					DialogoConsumo dialog;
					if(tipo.toString().equals("Gerente"))
					{
						dialog=new DialogoConsumo(idSucursal,mundo,false,11);
					}
					else
					{
						dialog=new DialogoConsumo(idSucursal,mundo,true,11);
					}
					dialog.setVisible(true);
					dispose();  


				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");

				}
			}
		});
		mnConsultar.add(opConsumoV2);

		opFuncionamientoProd.setText("Funcionamiento producto");
		opFuncionamientoProd.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	

					InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProductosRFC12(mundo.RFC12MasVendido(), mundo.RFC12MenosVendido()), idSucursal);
					inter.setVisible(true);
					dispose();

				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");

				}
			}
		});
		mnConsultar.add(opFuncionamientoProd);

		opFuncionamientoProv.setText("Funcionamiento proveedor");
		opFuncionamientoProv.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	

					InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelProveedorRFC12(mundo.RFC12MasSolicitado(), mundo.RFC12MenosSolicitado()), idSucursal);
					inter.setVisible(true);
					dispose();

				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");

				}
			}
		});
		mnConsultar.add(opFuncionamientoProv);

		opBuenosClientes.setText("Buenos Clientes");
		opBuenosClientes.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {	
					List<Comprador>compradores=mundo.RFC13BuenosClientesCompraCadaMes();
					compradores = Stream.concat(compradores.stream(), mundo.RFC13BuenosClientesCompraProductosCostosos().stream())
                            .collect(Collectors.toList());
					compradores = Stream.concat(compradores.stream(), mundo.RFC13BuenosClientesCompraTecnologiaHerramientas().stream())
                            .collect(Collectors.toList());
					
					InterfazEmpleados2 inter=new InterfazEmpleados2(mundo, new PanelCompradores(compradores), idSucursal);
					inter.setVisible(true);
					dispose();

				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
					JOptionPane.showMessageDialog(null, "Revision fallida \nIntentalo con otros datos");

				}
			}
		});
		mnConsultar.add(opBuenosClientes);



		menuEmpleado.add(mnConsultar);

		mnRecoger.setText("Recoger Carritos");
		mnRecoger.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mnRecogerMouseClicked(evt);
				try {
					mundo.requerimiento17();
					JOptionPane.showMessageDialog(null, "Recoleccion exitosa");
				} catch (Exception e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null, "Recoleccion fallida\nIntentalo mas tarde");
				}
			}
		});
		menuEmpleado.add(mnRecoger);

		setJMenuBar(menuEmpleado);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void opProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opProveedoresMouseClicked
		// TODO add your handling code here:
	}//GEN-LAST:event_opProveedoresMouseClicked

	private void mnRecogerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnRecogerMouseClicked
		// TODO add your handling code here:
	}//GEN-LAST:event_mnRecogerMouseClicked



	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel jPanel1;
	private javax.swing.JMenuBar menuEmpleado;
	private javax.swing.JMenu mnConsultar;
	private javax.swing.JMenu mnRecoger;
	private javax.swing.JMenu mnRegistrar;
	private javax.swing.JMenu opAnaOper;
	private javax.swing.JMenu opBodega;
	private javax.swing.JMenu opCliFrec;
	private javax.swing.JMenu opCompProv;
	private javax.swing.JMenu opDinero;
	private javax.swing.JMenu opEstante;
	private javax.swing.JMenu opLlegadaProducto;
	private javax.swing.JMenu opOcupacion;
	private javax.swing.JMenu opPedido;
	private javax.swing.JMenu opProdCarac;
	private javax.swing.JMenu opProdPocDemanda;
	private javax.swing.JMenu opProducto;
	private javax.swing.JMenu opPromocion;
	private javax.swing.JMenu opPromociones;
	private javax.swing.JMenu opProveedores;
	private javax.swing.JMenu opVentasUsu;
	private javax.swing.JMenu opConsumo;
	private javax.swing.JMenu opConsumoV2;
	private javax.swing.JMenu opFuncionamientoProd;
	private javax.swing.JMenu opFuncionamientoProv;
	private javax.swing.JMenu opBuenosClientes;
	// End of variables declaration//GEN-END:variables
}
