/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uniandes.isis2304.superAndes.interfazApp;

import javax.swing.JOptionPane;

import uniandes.isis2304.superAndes.persistencia.PersistenciaSuperAndes;

/**
 *
 * @author Andres
 */
public class InterfazCliente extends javax.swing.JFrame {

	private PersistenciaSuperAndes mundo;
	
	private String nombre;
	
	private String identificador;
	
    /**
     * Creates new form InterfazCliente
     */
    public InterfazCliente(PersistenciaSuperAndes mundo,String identificador,String nombre) {
    	this.identificador=identificador;
    	this.nombre=nombre;
    	this.mundo=mundo;
    	setResizable( false );
		setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCarrito = new javax.swing.JMenu();
        opSolicitar = new javax.swing.JMenu();
        opAbandonar = new javax.swing.JMenu();
        mnProducto = new javax.swing.JMenu();
        opAgregarProducto = new javax.swing.JMenu();
        opDevolverProducto = new javax.swing.JMenu();
        mnPagar = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Elige una opcion para ayudarte");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Bienvenid@");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uniandes/isis2304/superAndes/interfazApp/dataInterfaz/bienvenida.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel3)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(36, 36, 36))
        );

        mnCarrito.setText("Carrito De Compras");

        opSolicitar.setText("Solicitar");
        opSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opSolicitarMouseClicked(evt);
                try{
                    long idCarrito=mundo.requerimiento12(identificador);
                    JOptionPane.showMessageDialog(null, "Se le asigno el carrito con id "+idCarrito);
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "hubo un error inesperado intenta mas tarde");
                    } 
            }
        });
        mnCarrito.add(opSolicitar);

        opAbandonar.setText("Abandonar");
        opAbandonar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opSolicitarMouseClicked(evt);
                try{
                    mundo.requerimiento16(identificador);
                    JOptionPane.showMessageDialog(null, "Se abandono satisfacotiamente");
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "hubo un error inesperado intenta mas tarde");
                    } 
                
            }
        });        
        mnCarrito.add(opAbandonar);

        jMenuBar1.add(mnCarrito);

        mnProducto.setText("Producto");

        opAgregarProducto.setText("Agregar");
        opAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opSolicitarMouseClicked(evt);
                try{
                	String idProducto=JOptionPane.showInputDialog(null, "Ingrese el codigo del producto");
                	String idSucursal=JOptionPane.showInputDialog(null, "Ingrese el nombre de la sucursal en la que se encuentra");
                	String cantidad=JOptionPane.showInputDialog(null, "Ingrese la cantidad a comprar");
                	
                    mundo.requerimiento13(identificador,idProducto, idSucursal, Integer.parseInt(cantidad));
                    JOptionPane.showMessageDialog(null, "Se abandono satisfacotiamente");
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "hubo un error inesperado intenta mas tarde");
                    } 
                
            }
        });  
        mnProducto.add(opAgregarProducto);
       
        opDevolverProducto.setText("Devolver");
        opDevolverProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opSolicitarMouseClicked(evt);
                try{
                	String idProducto=JOptionPane.showInputDialog(null, "Ingrese el codigo del producto");
                	String idSucursal=JOptionPane.showInputDialog(null, "Ingrese el nombre de la sucursal en la que se encuentra");
                	String cantidad=JOptionPane.showInputDialog(null, "Ingrese la cantidad a comprar");
                	
                    mundo.requerimiento14(identificador,idProducto, idSucursal, Integer.parseInt(cantidad));
                    JOptionPane.showMessageDialog(null, "Se abandono satisfacotiamente");
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Hubo un error inesperado intenta mas tarde");
                    } 
                
            }
        });  
        mnProducto.add(opDevolverProducto);

        jMenuBar1.add(mnProducto);

        mnPagar.setText("Pagar ");
        mnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opSolicitarMouseClicked(evt);
                try{
                	
                   // mundo.requerimiento15(docComprador);
                    JOptionPane.showMessageDialog(null, "Pago exitoso");
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "hubo un error inesperado intenta mas tarde");
                    } 
                
            }
        }); 
        jMenuBar1.add(mnPagar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opSolicitarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_opSolicitarMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnCarrito;
    private javax.swing.JMenu mnPagar;
    private javax.swing.JMenu mnProducto;
    private javax.swing.JMenu opAbandonar;
    private javax.swing.JMenu opAgregarProducto;
    private javax.swing.JMenu opDevolverProducto;
    private javax.swing.JMenu opSolicitar;
    // End of variables declaration//GEN-END:variables
}
