/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uniandes.isis2304.superAndes.interfazApp;

import java.util.List;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import main.java.model.IndiceBodega;
import main.java.model.Productos;

/**
 *
 * @author Andres
 */
public class PanelProductos extends javax.swing.JPanel implements ListSelectionListener{
	
	private List<Productos>productos;
	private Productos prodActual;

    /**
     * Creates new form PanelProductos
     */
    public PanelProductos(List<Productos>productos) {
    	this.productos=productos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        scrollList = new javax.swing.JScrollPane();
        listProductos = new javax.swing.JList<>();
        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblValCod = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblValNom = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblValMarca = new javax.swing.JLabel();
        lblVolumen = new javax.swing.JLabel();
        lblValVol = new javax.swing.JLabel();
        lblPresentacion = new javax.swing.JLabel();
        lblValPres = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblValPeso = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblValTipo = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uniandes/isis2304/superAndes/interfazApp/dataInterfaz/productos.png"))); // NOI18N
        lblImagen.setText("\n");

        listProductos.addListSelectionListener( this );
        listProductos.setListData(productos.toArray());
		listProductos.setToolTipText("Productos");
        scrollList.setViewportView(listProductos);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setText("Productos dada la caracteristica");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblCodigo.setText("Codigo de Barras:");

        lblValCod.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValCod.setText("jLabel2");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNombre.setText("Nombre:");

        lblValNom.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValNom.setText("jLabel2");

        lblMarca.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblMarca.setText("Marca:");

        lblValMarca.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValMarca.setText("jLabel2");

        lblVolumen.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblVolumen.setText("Volumen:");

        lblValVol.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValVol.setText("jLabel2");

        lblPresentacion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPresentacion.setText("Presentacion:");

        lblValPres.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValPres.setText("jLabel2");

        lblPeso.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPeso.setText("Peso:");

        lblValPeso.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValPeso.setText("jLabel2");

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTipo.setText("Tipo:");

        lblValTipo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValTipo.setText("jLabel2");

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uniandes/isis2304/superAndes/interfazApp/dataInterfaz/productos.png"))); // NOI18N
        lblImagen1.setText("\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValNom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValCod))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValMarca))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValTipo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblVolumen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblValVol))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPresentacion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblValPres))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblPeso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblValPeso)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(lblImagen1)))))
                .addGap(28, 28, 28)
                .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollList))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCodigo)
                                    .addComponent(lblValCod))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombre)
                                    .addComponent(lblValNom))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTipo)
                                    .addComponent(lblValTipo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMarca)
                                    .addComponent(lblValMarca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPresentacion)
                                    .addComponent(lblValPres))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblVolumen)
                                    .addComponent(lblValVol))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPeso)
                                    .addComponent(lblValPeso))
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblImagen1)))))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPresentacion;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValCod;
    private javax.swing.JLabel lblValMarca;
    private javax.swing.JLabel lblValNom;
    private javax.swing.JLabel lblValPeso;
    private javax.swing.JLabel lblValPres;
    private javax.swing.JLabel lblValTipo;
    private javax.swing.JLabel lblValVol;
    private javax.swing.JLabel lblVolumen;
    private javax.swing.JList listProductos;
    private javax.swing.JScrollPane scrollList;
    // End of variables declaration//GEN-END:variables

	@Override
	public void valueChanged(ListSelectionEvent e) {
		// TODO Auto-generated method stub
		prodActual = ( Productos )listProductos.getSelectedValue( );
		if( prodActual != null )
		{
			lblValCod.setText(prodActual.getCodigoBarras());
			lblValMarca.setText(prodActual.getMarca());
			lblValNom.setText(prodActual.getNombre());
			lblValPeso.setText(prodActual.getCantidadPeso()+prodActual.getUnidadPeso());
			lblValVol.setText(prodActual.getCantidad()+prodActual.getUnidadVolumen());
			lblValPres.setText(prodActual.getPresentacion());
			lblValTipo.setText(prodActual.getTipoProducto());
		}
	}
}
