/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uniandes.isis2304.superAndes.interfazApp;

import java.awt.event.ActionListener;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import main.java.model.IndiceBodega;
import main.java.model.IndiceEstante;

/**
 *
 * @author Andres
 */
public class PanelBodegaEstantes extends javax.swing.JPanel  implements  ListSelectionListener {

	private List<IndiceBodega> bodegas;
	private List<IndiceEstante> estantes;
	private IndiceBodega bodegaAct;
	private IndiceEstante estanteAct;

	/**
	 * Creates new form PanelBodegaEstantes
	 */
	public PanelBodegaEstantes(List<IndiceBodega>bodegas,List<IndiceEstante>estantes) {
		this.bodegas=bodegas;
		this.estantes=estantes;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblTitulo = new javax.swing.JLabel();
		lblCapVolEst = new javax.swing.JLabel();
		lblValCapVolEst = new javax.swing.JLabel();
		lblOcuEst = new javax.swing.JLabel();
		lblValOcuEst = new javax.swing.JLabel();
		lblImagen = new javax.swing.JLabel();
		lblIdEst = new javax.swing.JLabel();
		lblValEst = new javax.swing.JLabel();
		scrollList = new javax.swing.JScrollPane();
		listBodegas = new javax.swing.JList<>();
		scrollList1 = new javax.swing.JScrollPane();
		listEstantes = new javax.swing.JList<>();
		lblBodegas = new javax.swing.JLabel();
		lblEstantes = new javax.swing.JLabel();
		lblOcuBod = new javax.swing.JLabel();
		lblValOcuBod = new javax.swing.JLabel();
		lblIdBod = new javax.swing.JLabel();
		lblValIdBod = new javax.swing.JLabel();
		lblCapBod = new javax.swing.JLabel();
		lblValCapBod = new javax.swing.JLabel();

		lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
		lblTitulo.setText("Ocupacion de Bodega/Estante");

		lblCapVolEst.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblCapVolEst.setText("Capacidad Vol:");

		lblValCapVolEst.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblValCapVolEst.setText(" ");

		lblOcuEst.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblOcuEst.setText("Ocupacion:");

		lblValOcuEst.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblValOcuEst.setText(" ");

		lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uniandes/isis2304/superAndes/interfazApp/dataInterfaz/bodega.png"))); // NOI18N
		lblImagen.setText("\n");

		lblIdEst.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblIdEst.setText("Id:");

		lblValEst.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblValEst.setText(" ");

		listBodegas.addListSelectionListener( this );
		listBodegas.setListData(bodegas.toArray());
		listBodegas.setToolTipText("Bodegas");
		scrollList.setViewportView(listBodegas);

		listEstantes.addListSelectionListener( this );
		listEstantes.setListData(estantes.toArray());
		listEstantes.setToolTipText("Estantes");
		scrollList1.setViewportView(listEstantes);

		lblBodegas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		lblBodegas.setForeground(new java.awt.Color(102, 204, 255));
		lblBodegas.setText("Bodegas");

		lblEstantes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		lblEstantes.setForeground(new java.awt.Color(102, 204, 255));
		lblEstantes.setText("Estantes");

		lblOcuBod.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblOcuBod.setText("Ocupacion:");

		lblValOcuBod.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblValOcuBod.setText(" ");

		lblIdBod.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblIdBod.setText("Id:");

		lblValIdBod.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblValIdBod.setText(" ");

		lblCapBod.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblCapBod.setText("Capacidad Vol:");

		lblValCapBod.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		lblValCapBod.setText(" ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGap(41, 41, 41)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(lblTitulo)
										.addGap(38, 38, 38)
										.addComponent(lblEstantes)
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(layout.createSequentialGroup()
																		.addGap(10, 10, 10)
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(layout.createSequentialGroup()
																						.addComponent(lblCapBod)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(lblValCapBod))
																				.addGroup(layout.createSequentialGroup()
																						.addComponent(lblOcuBod)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(lblValOcuBod))
																				.addGroup(layout.createSequentialGroup()
																						.addComponent(lblIdBod)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(lblValIdBod))))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(lblIdEst)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(lblValEst))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(lblOcuEst)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(lblValOcuEst))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(lblCapVolEst)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(lblValCapVolEst)))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
														.addGap(0, 0, Short.MAX_VALUE)
														.addComponent(lblImagen)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(scrollList1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(scrollList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
														.addComponent(lblBodegas)
														.addGap(38, 38, 38)))))
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGap(0, 36, Short.MAX_VALUE)
										.addComponent(lblEstantes)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(scrollList1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addContainerGap()
										.addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblIdEst)
												.addComponent(lblValEst))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblCapVolEst)
												.addComponent(lblValCapVolEst))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblOcuEst)
												.addComponent(lblValOcuEst))
										.addGap(6, 6, 6)))
						.addGap(18, 18, 18)
						.addComponent(lblBodegas)
						.addGap(2, 2, 2)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap())
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblIdBod)
												.addComponent(lblValIdBod))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblCapBod)
												.addComponent(lblValCapBod))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblOcuBod)
												.addComponent(lblValOcuBod))
										.addGap(52, 52, 52))))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(lblImagen)
						.addGap(152, 152, 152))
				);
	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel lblBodegas;
	private javax.swing.JLabel lblCapBod;
	private javax.swing.JLabel lblCapVolEst;
	private javax.swing.JLabel lblEstantes;
	private javax.swing.JLabel lblIdBod;
	private javax.swing.JLabel lblIdEst;
	private javax.swing.JLabel lblImagen;
	private javax.swing.JLabel lblOcuBod;
	private javax.swing.JLabel lblOcuEst;
	private javax.swing.JLabel lblTitulo;
	private javax.swing.JLabel lblValCapBod;
	private javax.swing.JLabel lblValCapVolEst;
	private javax.swing.JLabel lblValEst;
	private javax.swing.JLabel lblValIdBod;
	private javax.swing.JLabel lblValOcuBod;
	private javax.swing.JLabel lblValOcuEst;
	private JList listBodegas;
	private JList listEstantes;
	private javax.swing.JScrollPane scrollList;
	private javax.swing.JScrollPane scrollList1;
	// End of variables declaration//GEN-END:variables

	@Override
	public void valueChanged(ListSelectionEvent arg0) {
		// TODO Auto-generated method stub
		bodegaAct = ( IndiceBodega )listBodegas.getSelectedValue( );
		if( bodegaAct != null )
		{
			lblValCapBod.setText(bodegaAct.getCapacidadVolumen()+bodegaAct.getUnidBodega());
			lblValIdBod.setText(bodegaAct.getIdBodega()+"");
			lblValOcuBod.setText(bodegaAct.darIndiceAlmacenamiento()+"");
		}
		estanteAct = ( IndiceEstante )listEstantes.getSelectedValue( );
		if( estanteAct != null )
		{
			lblValCapVolEst.setText(estanteAct.getCapacidadVolumen()+estanteAct.getUnidEstante());
			lblValEst.setText(estanteAct.getIdEstante()+"");
			lblValOcuEst.setText(estanteAct.darIndiceAlmacenamiento()+"");
		}
	}
}
