/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uniandes.isis2304.superAndes.interfazApp;

import java.util.List;

import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import main.java.model.IndiceBodega;
import main.java.model.UsuariosComprasRFC10;

/**
 *
 * @author Andres
 */
public class PanelCompradoresRFC10 extends javax.swing.JPanel implements  ListSelectionListener {

	private List<UsuariosComprasRFC10>compradores;

	private UsuariosComprasRFC10 compActual;

	/**
	 * Creates new form PanelCompradores
	 */
	public PanelCompradoresRFC10(List<UsuariosComprasRFC10>compradores) {
		this.compradores=compradores;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollList = new javax.swing.JScrollPane();
        listCompradoresRFC10 = new javax.swing.JList<>();
        lblTitulo = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblValDoc = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblValNom = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblValFecha = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblValEmail = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();
        lblPuntos1 = new javax.swing.JLabel();
        lblValCodProd = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        lblValCantVen = new javax.swing.JLabel();

        listCompradoresRFC10.addListSelectionListener( this );
        listCompradoresRFC10.setListData(compradores.toArray());
        listCompradoresRFC10.setToolTipText("Compradores");;
        scrollList.setViewportView(listCompradoresRFC10);


        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setText("Compradores");

        lblDocumento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDocumento.setText("Documento:");

        lblValDoc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValDoc.setText(" ");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNombre.setText("Nombre:");

        lblValNom.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValNom.setText(" ");

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblFecha.setText("Fecha:");

        lblValFecha.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValFecha.setText(" ");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblEmail.setText("Email:");

        lblValEmail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValEmail.setText(" ");

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uniandes/isis2304/superAndes/interfazApp/dataInterfaz/compradores.png"))); // NOI18N
        lblImagen1.setText(" ");

        lblPuntos1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPuntos1.setText("Codigo producto:");

        lblValCodProd.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValCodProd.setText(" ");

        lblEmail1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblEmail1.setText("Cantidad Vendida:");

        lblValCantVen.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValCantVen.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValNom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDocumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValDoc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPuntos1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValCodProd))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValCantVen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocumento)
                            .addComponent(lblValDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(lblValNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(lblValEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(lblValFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuntos1)
                            .addComponent(lblValCodProd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail1)
                            .addComponent(lblValCantVen))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntos1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValCantVen;
    private javax.swing.JLabel lblValCodProd;
    private javax.swing.JLabel lblValDoc;
    private javax.swing.JLabel lblValEmail;
    private javax.swing.JLabel lblValFecha;
    private javax.swing.JLabel lblValNom;
    private javax.swing.JList listCompradoresRFC10;
    private javax.swing.JScrollPane scrollList;
    // End of variables declaration//GEN-END:variables

	@Override
	public void valueChanged(ListSelectionEvent arg0) {
		// TODO Auto-generated method stub
		compActual = ( UsuariosComprasRFC10 )listCompradoresRFC10.getSelectedValue( );
		if( compActual != null )
		{
			lblValDoc.setText(compActual.getIdentificador());
			lblValEmail.setText(compActual.getCorreoElectronico());
			lblValNom.setText(compActual.getNombre());
			lblValCantVen.setText(compActual.getCantidadVendida()+"");
			lblValCodProd.setText(compActual.getCodigoProducto());
			lblValFecha.setText(compActual.getFecha().toString());
		}

	}
}
