/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uniandes.isis2304.superAndes.interfazApp;

import java.util.List;

import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import main.java.model.Comprador;
import main.java.model.IndiceBodega;

/**
 *
 * @author Andres
 */
public class PanelCompradores extends javax.swing.JPanel implements  ListSelectionListener {

	private List<Comprador>compradores;
	
	private Comprador compActual;
	
    /**
     * Creates new form PanelCompradores
     */
    public PanelCompradores(List<Comprador>compradores) {
    	this.compradores=compradores;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollList = new javax.swing.JScrollPane();
        listCompradores = new javax.swing.JList<>();
        lblTitulo = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblValDoc = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblValNom = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        lblValPuntos = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblValEmail = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();

        listCompradores.addListSelectionListener( this );
        listCompradores.setListData(compradores.toArray());
        listCompradores.setToolTipText("Compradores");;
        scrollList.setViewportView(listCompradores);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setText("Compradores");

        lblDocumento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDocumento.setText("Documento:");

        lblValDoc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValDoc.setText("");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNombre.setText("Nombre:");

        lblValNom.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValNom.setText("");

        lblPuntos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPuntos.setText("Puntos:");

        lblValPuntos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValPuntos.setText("");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblEmail.setText("Email:");

        lblValEmail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValEmail.setText("");

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uniandes/isis2304/superAndes/interfazApp/dataInterfaz/compradores.png"))); // NOI18N
       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValNom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDocumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValDoc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPuntos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValPuntos)
                                .addGap(18, 18, 18)
                                .addComponent(lblImagen1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumento)
                    .addComponent(lblValDoc))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(lblValNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(lblValEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuntos)
                            .addComponent(lblValPuntos))
                        .addGap(91, 106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImagen1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValDoc;
    private javax.swing.JLabel lblValEmail;
    private javax.swing.JLabel lblValNom;
    private javax.swing.JLabel lblValPuntos;
    private javax.swing.JList listCompradores;
    private javax.swing.JScrollPane scrollList;
    // End of variables declaration//GEN-END:variables

	@Override
	public void valueChanged(ListSelectionEvent arg0) {
		// TODO Auto-generated method stub
		compActual = ( Comprador )listCompradores.getSelectedValue( );
		if( compActual != null )
		{
			lblValDoc.setText(compActual.getIdentificador());
			lblValEmail.setText(compActual.getCorreoElectronico());
			lblValNom.setText(compActual.getNombre());
			lblValPuntos.setText(compActual.getPuntos()+"");

		}
		
	}
}
