/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uniandes.isis2304.superAndes.interfazApp;

import java.util.List;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import main.java.model.FacturasComprador;
import main.java.model.IndiceBodega;

/**
 *
 * @author Andres
 */
public class PanelFacturasComprador extends javax.swing.JPanel implements  ListSelectionListener {

	private List<FacturasComprador> facturas;
	
	private FacturasComprador factActual;
	
    /**
     * Creates new form PanelFacturasComprador
     */
    public PanelFacturasComprador(List<FacturasComprador>facturas) {
    	this.facturas=facturas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollList = new javax.swing.JScrollPane();
        listFacturas = new javax.swing.JList<>();
        lblTitulo = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblValNum = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblValFecha = new javax.swing.JLabel();
        lblIdSucursal = new javax.swing.JLabel();
        lblValIdSuc = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblValDocumento = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();

        listFacturas.addListSelectionListener( this );
        listFacturas.setListData(facturas.toArray());
        listFacturas.setToolTipText("Facturas");
        scrollList.setViewportView(listFacturas);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setText("Facturas Del Comprador");

        lblNumero.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNumero.setText("Numero Factura:");

        lblValNum.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValNum.setText(" ");

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblFecha.setText("Fecha de Compra:");

        lblValFecha.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValFecha.setText(" ");

        lblIdSucursal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblIdSucursal.setText("Id Sucursal:");

        lblValIdSuc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValIdSuc.setText(" ");

        lblDocumento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDocumento.setText("Documento Comprador");

        lblValDocumento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblValDocumento.setText(" ");

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uniandes/isis2304/superAndes/interfazApp/dataInterfaz/facturas.png"))); // NOI18N
        lblImagen1.setText("\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                            .addComponent(lblImagen1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFecha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblValFecha))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNumero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblValNum))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblIdSucursal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblValIdSuc))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDocumento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblValDocumento))))))
                .addGap(28, 28, 28)
                .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollList))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumero)
                                    .addComponent(lblValNum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFecha)
                                    .addComponent(lblValFecha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDocumento)
                                    .addComponent(lblValDocumento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIdSucursal)
                                    .addComponent(lblValIdSuc))
                                .addGap(91, 187, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblImagen1)))))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIdSucursal;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValDocumento;
    private javax.swing.JLabel lblValFecha;
    private javax.swing.JLabel lblValIdSuc;
    private javax.swing.JLabel lblValNum;
    private javax.swing.JList listFacturas;
    private javax.swing.JScrollPane scrollList;
    // End of variables declaration//GEN-END:variables

	@Override
	public void valueChanged(ListSelectionEvent e) {
		// TODO Auto-generated method stub
		factActual = ( FacturasComprador )listFacturas.getSelectedValue( );
		if( factActual != null )
		{
			lblValDocumento.setText(factActual.getIdComprador());
			lblValFecha.setText(factActual.getFecha().toString());
			lblValIdSuc.setText(factActual.getIdSucursal()+"");
			lblValNum.setText(factActual.getNumero()+"");
		}
		
	}
}
